### ISSUE TITLE
AWS Lambda supports Ruby 2.7

### ISSUE THREAD

**Issue by macejmic** [loganb/lambda-layer-cake#5]
Issue:

build-ruby2.5 is hardcoded in the code https://github.com/loganb/lambda-layer-cake/blob/6375bc7b6ee1594cdd49957c38704ea68b79d11d/lib/lambda_layer_cake/rake_helper.rb

Solution:

Let's extract it to an ENV variable or so since I would like to use ruby2.7.

https://aws.amazon.com/about-aws/whats-new/2020/02/aws-lambda-supports-ruby-2-7/

**Comment by loganb** [comment]
Thanks for opening an issue! I think we can read the ruby version out of your Gemfile and select the appropriate image without any additional configuration. 

It should be possible to simply parse the RUBY_VERSION constant right around here: https://github.com/loganb/lambda-layer-cake/blob/master/lib/lambda_layer_cake/rake_helper.rb#L29

Making a spec for that will likely be harder. Shoot over a PR if you can, but otherwise, I'll take a look in the next few days.

**Comment by loganb** [comment]
Pushed version 0.2.0, which now reads the version of the executing ruby version and uses a matching Lambda image.

**Comment by macejmic** [comment]
@loganb thank you! no need for a fork from now on.
